os:
  - linux
dist: xenial

language: c

cache:
  directories:
    - "$HOME/.choosenim"
    - "$HOME/csources"

env:
  global:
    - TAG="v0.20.0"
    - CHOOSENIM_CHOOSE_VERSION="0.20.0"
    - CHOOSENIM_NO_ANALYTICS=1
    - PATH="$PWD/bin${PATH:+:$PATH}"
    - CPU=amd64

install:
  - git clone --depth 1 --branch $TAG https://github.com/nim-lang/csources.git

before_script:
  - make -C csources -j 2 LD=$CC ucpu=$CPU

script:
  - nim c -d:ssl -d:release -r package_scanner.nim

notifications:
  email: false # noisy
